In [1]:
import torch
import torchvision

In [2]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.get_device_name()

'Quadro M1000M'

In [3]:
!nvidia-smi

Tue Nov  8 07:01:35 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 522.06       Driver Version: 522.06       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M1000M      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    N/A /  N/A |      0MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
a = torch.tensor([1])
a

tensor([1])

In [5]:
b = torch.tensor([[1,2,3],[2,3,4],[1,2,3],[2,3,4]])
b

tensor([[1, 2, 3],
        [2, 3, 4],
        [1, 2, 3],
        [2, 3, 4]])

In [6]:
display(
a.shape,a.size(),
    b.shape,b.size(),b.dtype
)

torch.Size([1])

torch.Size([1])

torch.Size([4, 3])

torch.Size([4, 3])

torch.int64

In [7]:
c = torch.FloatTensor([[21,3,2],[4,3,2],[1,2,1]])
print(c)

tensor([[21.,  3.,  2.],
        [ 4.,  3.,  2.],
        [ 1.,  2.,  1.]])


In [8]:
c.mean()

tensor(4.3333)

In [9]:
c.dtype

torch.float32

In [10]:
three_dim = torch.randn(2,3,4)
three_dim

tensor([[[-2.0852,  1.2965,  1.4074,  0.6420],
         [ 0.5549,  1.0517, -1.8096,  0.0287],
         [ 0.3156, -0.3353, -0.0176, -0.6429]],

        [[ 0.1716, -2.0588,  1.8044,  1.5300],
         [ 0.5106,  0.2559,  0.4634,  0.2760],
         [-1.0127, -0.5422, -1.3108, -1.0051]]])

In [11]:
display(
    "b:",b,
    'b.view(1,-1)',
    b.view(1,-1),
    'b.view(-1,1)',
    b.view(-1,1),
    'b.view(-1,4)',
    b.view(-1,4),
    'three_dim',
    three_dim,
    'three_dim.view(-1,1)',
    three_dim.view(-1,1),
    'three_dim.view(2,-1)',
    three_dim.view(2,-1),
    
       )

'b:'

tensor([[1, 2, 3],
        [2, 3, 4],
        [1, 2, 3],
        [2, 3, 4]])

'b.view(1,-1)'

tensor([[1, 2, 3, 2, 3, 4, 1, 2, 3, 2, 3, 4]])

'b.view(-1,1)'

tensor([[1],
        [2],
        [3],
        [2],
        [3],
        [4],
        [1],
        [2],
        [3],
        [2],
        [3],
        [4]])

'b.view(-1,4)'

tensor([[1, 2, 3, 2],
        [3, 4, 1, 2],
        [3, 2, 3, 4]])

'three_dim'

tensor([[[-2.0852,  1.2965,  1.4074,  0.6420],
         [ 0.5549,  1.0517, -1.8096,  0.0287],
         [ 0.3156, -0.3353, -0.0176, -0.6429]],

        [[ 0.1716, -2.0588,  1.8044,  1.5300],
         [ 0.5106,  0.2559,  0.4634,  0.2760],
         [-1.0127, -0.5422, -1.3108, -1.0051]]])

'three_dim.view(-1,1)'

tensor([[-2.0852],
        [ 1.2965],
        [ 1.4074],
        [ 0.6420],
        [ 0.5549],
        [ 1.0517],
        [-1.8096],
        [ 0.0287],
        [ 0.3156],
        [-0.3353],
        [-0.0176],
        [-0.6429],
        [ 0.1716],
        [-2.0588],
        [ 1.8044],
        [ 1.5300],
        [ 0.5106],
        [ 0.2559],
        [ 0.4634],
        [ 0.2760],
        [-1.0127],
        [-0.5422],
        [-1.3108],
        [-1.0051]])

'three_dim.view(2,-1)'

tensor([[-2.0852,  1.2965,  1.4074,  0.6420,  0.5549,  1.0517, -1.8096,  0.0287,
          0.3156, -0.3353, -0.0176, -0.6429],
        [ 0.1716, -2.0588,  1.8044,  1.5300,  0.5106,  0.2559,  0.4634,  0.2760,
         -1.0127, -0.5422, -1.3108, -1.0051]])

In [12]:
r = torch.randn(4,4)
r

tensor([[ 0.9626,  1.3798, -0.1716, -0.4546],
        [-0.6733,  1.3833,  1.3515,  1.1742],
        [ 0.5177, -1.9347, -0.8862, -1.4484],
        [ 1.1314, -0.6441,  0.1888,  0.4291]])

In [13]:
r = torch.rand(4,4)
r

tensor([[0.6744, 0.6161, 0.6753, 0.2611],
        [0.3001, 0.1645, 0.7491, 0.7572],
        [0.9026, 0.5263, 0.8741, 0.7920],
        [0.7478, 0.7653, 0.0284, 0.7885]])

In [19]:
int_arr = torch.randint(6,10,(4,4))
int_arr

tensor([[9, 8, 7, 6],
        [9, 6, 6, 6],
        [8, 6, 8, 9],
        [7, 7, 7, 6]])

In [20]:
torch.numel(int_arr)

16

In [28]:
z = torch.zeros(3,3,dtype=torch.int64)
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.zero_(int_arr)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [31]:
int_arr

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [32]:
torch.zeros_like(three_dim)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [33]:
torch.rand_like(three_dim)

tensor([[[0.4757, 0.2558, 0.2533, 0.7494],
         [0.5893, 0.1677, 0.5687, 0.1579],
         [0.3362, 0.8865, 0.5379, 0.6909]],

        [[0.3163, 0.1390, 0.3230, 0.7153],
         [0.2439, 0.1324, 0.3043, 0.7885],
         [0.1149, 0.8870, 0.7444, 0.4091]]])

In [37]:
new_three_dim=torch.randint_like(three_dim,0,2,dtype=torch.int64)
new_three_dim

tensor([[[1, 0, 1, 1],
         [0, 0, 1, 0],
         [1, 0, 0, 1]],

        [[1, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 1, 1, 1]]])

In [38]:
new_three_dim.add(1)

tensor([[[2, 1, 2, 2],
         [1, 1, 2, 1],
         [2, 1, 1, 2]],

        [[2, 1, 1, 1],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [42]:
torch.add(new_three_dim,1),new_three_dim.shape

(tensor([[[2, 1, 2, 2],
          [1, 1, 2, 1],
          [2, 1, 1, 2]],
 
         [[2, 1, 1, 1],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]]),
 torch.Size([2, 3, 4]))

In [44]:
torch.add(new_three_dim,torch.ones_like(new_three_dim)*10)

tensor([[[11, 10, 11, 11],
         [10, 10, 11, 10],
         [11, 10, 10, 11]],

        [[11, 10, 10, 10],
         [10, 10, 10, 10],
         [11, 11, 11, 11]]])

In [52]:
new_three_dim.add_(torch.ones_like(new_three_dim)*10)

tensor([[[71, 70, 71, 71],
         [70, 70, 71, 70],
         [71, 70, 70, 71]],

        [[71, 70, 70, 70],
         [70, 70, 70, 70],
         [71, 71, 71, 71]]])

In [64]:
new_three_dim = new_three_dim.view(4,-1)
new_three_dim

tensor([[71, 70, 71, 71, 70, 70],
        [71, 70, 71, 70, 70, 71],
        [71, 70, 70, 70, 70, 70],
        [70, 70, 71, 71, 71, 71]])

In [67]:
display({
    'new_three_dim[:,1]':new_three_dim[:,1],
    'new_three_dim[:,:2]':new_three_dim[:,:2],
    'new_three_dim[:3,:]':new_three_dim[:3,:],
    'new_three_dim[2,3]':new_three_dim[2,3],
    })

{'new_three_dim[:,1]': tensor([70, 70, 70, 70]),
 'new_three_dim[:,:2]': tensor([[71, 70],
         [71, 70],
         [71, 70],
         [70, 70]]),
 'new_three_dim[:3,:]': tensor([[71, 70, 71, 71, 70, 70],
         [71, 70, 71, 70, 70, 71],
         [71, 70, 70, 70, 70, 70]]),
 'new_three_dim[2,3]': tensor(70)}

# numpy bridge

In [68]:
import numpy as np

In [71]:
torch.cuda.is_available()

False